import{S as f,a as w,i as E}from"./assets/vendor-bad0427b.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const I="https://pixabay.com/api/",P="41701983-23ca5d5908e2c78927e8095f2",d=40,L=new f(".gallery-item"),b=()=>{const e=new URL(I);return e.searchParams.append("key",P),e.searchParams.append("image_type","photo"),e.searchParams.append("orientation","horizontal"),e.searchParams.append("safesearch",!0),e},m=async(e,a=1)=>{try{const t=b();return t.searchParams.append("q",e),t.searchParams.append("page",a),t.searchParams.append("per_page",d),(await w.get(t.toString())).data.hits}catch(t){throw console.error("Error fetching images:",t),t}},u=e=>{const a=document.getElementById("gallery");e.forEach(t=>{const{webformatURL:n,largeImageURL:r,tags:o,likes:c,views:h,comments:p,downloads:y}=t;a.insertAdjacentHTML("beforeend",`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${n}" alt="${o}"/>
      </a>
      <div class="image-info">
        <p>Likes: ${c}</p>
        <p>Views: ${h}</p>
        <p>Comments: ${p}</p>
        <p>Downloads: ${y}</p>
      </div>
    </li>
    `)}),L.refresh()},g=()=>{document.querySelector(".loader").style.display="block"},i=()=>{document.querySelector(".loader").style.display="none"},s=(e,a="info")=>{E[a]({title:e,position:"topCenter"})},B=async e=>{e.preventDefault();const t=document.getElementById("search-input").value.trim();if(t.length<3){s("Please enter a search query with at least 3 characters","warning");return}try{g();const n=await m(t);i(),n.length>0?(u(n),document.getElementById("load-more").style.display=n.length>=d?"block":"none"):s("Sorry, there are no images matching your search query. Please try again.","error")}catch{i(),s("Error fetching images. Please try again later.","error")}};let l=1;const S=async()=>{const a=document.getElementById("search-input").value.trim();if(a.length<3){s("Please enter a search query with at least 3 characters","warning");return}try{g();const t=await m(a,l+1);i(),t.length>0?(u(t),l++,window.scrollBy(0,q())):(s("No more images to load","info"),document.getElementById("load-more").style.display="none")}catch{i(),s("Error fetching images. Please try again later.","error")}},q=()=>{const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0},v=document.getElementById("form");v.addEventListener("submit",B);const $=document.getElementById("load-more");$.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
