import{s as i,a as f,i as E}from"./assets/vendor-2b14a7bb.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const I="https://pixabay.com/api/",w="41701983-23ca5d5908e2c78927e8095f2",P=40;new i(".gallery-item");const L=()=>{const e=new URL(I);return e.searchParams.append("key",w),e.searchParams.append("image_type","photo"),e.searchParams.append("orientation","horizontal"),e.searchParams.append("safesearch",!0),e},m=async(e,a=1)=>{try{const t=L();return t.searchParams.append("q",e),t.searchParams.append("page",a),t.searchParams.append("per_rage",P),(await f.get(t.toString())).data.hits}catch(t){throw console.error("Error fetching images:",t),t}},g=e=>{const a=document.getElementById("gallery");e.forEach(t=>{const{webformatURL:o,largeImageURL:r,tags:n,likes:c,views:h,comments:p,downloads:y}=t;a.insertAdjacentHTML("beforeend",`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${o}" alt="${n}"/>
      </a>
      <div class="image-info">
        <p>Likes: ${c}</p>
        <p>Views: ${h}</p>
        <p>Comments: ${p}</p>
        <p>Downloads: ${y}</p>
      </div>
    </li>
    `)})},u=()=>{document.getElementById("loader").style.display="block"},l=()=>{document.getElementById("loader").style.display="none"},s=(e,a="info")=>{i.close(),i.reload(),i.refresh(),i.next(),E[a]({title:e,position:"topCenter"})},B=async e=>{e.preventDefault();const t=document.getElementById("search-input").value.trim();if(t.length<3){s("Please enter a search query with at least 3 characters","warning");return}u();try{const o=await m(t);l(),o.length>0?(g(o),document.getElementById("load-more").style.display="block"):s("Sorry, there are no images matching your search query. Please try again.","error")}catch{l(),s("Error fetching images. Please try again later.","error")}},b=async()=>{const a=document.getElementById("search-input").value.trim();if(a.length<3){s("Please enter a search query with at least 3 characters","warning");return}u();try{const t=await m(a,d);l(),t.length>0?(g(t),d++,window.scrollBy(0,v())):(s("No more images t load","info"),document.getElementById("load-more").style.display="none")}catch{l(),s("Error fetching images. Please try again later.","error")}},v=()=>{const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0};let d=1;const q=document.getElementById("form");q.addEventListener("submit",B);const S=document.getElementById("load-more");S.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
